apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
type: Opaque
data:
  # Default password: v8hlDV0yMAHHlIurYupj (base64 encoded)
  # In production, change this password and use proper secret management
  POSTGRES_PASSWORD: djhobERWMHlNQUhIbEl1cll1cGo=
