apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: cardano-testnet-combined

resources:
- namespace.yaml
- ../../base/common
- ../../base/postgres
- ../../base/cardano-combined

patches:
- path: network-config-patch.yaml
- path: storage-patch.yaml

configMapGenerator:
- name: common-env
  behavior: merge
  literals:
  - NETWORK=preprod
  - MITHRIL_AGGREGATOR_ENDPOINT=https://aggregator.release-preprod.api.mithril.network/aggregator

namespace: cardano-testnet-combined
