apiVersion: v1
kind: Service
metadata:
  name: cardano-db-sync
spec:
  type: ClusterIP
  ports:
  - port: 8080
    targetPort: 8080
    protocol: TCP
    name: prometheus
  selector:
    app: cardano-db-sync
