apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mithril-snapshot-cache
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 100Gi
  storageClassName: "longhorn"  # Use default storage class or specify as needed